.TH "simple_list" 3 "Sat Feb 20 2016" "Version 1.0" "Web Download" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simple_list \- Struct for list\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBsimple_list\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBstring\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for list\&. 

Used to list character strings of new requests 
.SH "Field Documentation"
.PP 
.SS "struct \fBsimple_list\fP* next"
pointer to the next element of the list 
.SS "char* string"
character string 

.SH "Author"
.PP 
Generated automatically by Doxygen for Web Download from the source code\&.
